-- PostgreSQL DDL and seed data for ai_mcp_gateway

DROP TABLE IF EXISTS public.mcp_protocol_mapping;
DROP TABLE IF EXISTS public.mcp_protocol_registry;
DROP TABLE IF EXISTS public.mcp_gateway_auth;
DROP TABLE IF EXISTS public.mcp_gateway;

CREATE OR REPLACE FUNCTION public.update_update_time()
RETURNS trigger AS $$
BEGIN
  NEW.update_time = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE public.mcp_gateway (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  gateway_id varchar(64) NOT NULL,
  gateway_name varchar(128) NOT NULL,
  gateway_desc varchar(512),
  status smallint NOT NULL DEFAULT 1,
  create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_mcp_gateway PRIMARY KEY (id),
  CONSTRAINT uk_gateway_id UNIQUE (gateway_id)
);

COMMENT ON TABLE public.mcp_gateway IS 'MCP网关配置表';
COMMENT ON COLUMN public.mcp_gateway.id IS '主键ID';
COMMENT ON COLUMN public.mcp_gateway.gateway_id IS '网关唯一标识';
COMMENT ON COLUMN public.mcp_gateway.gateway_name IS '网关名称';
COMMENT ON COLUMN public.mcp_gateway.gateway_desc IS '网关描述';
COMMENT ON COLUMN public.mcp_gateway.status IS '状态：0-禁用，1-启用';
COMMENT ON COLUMN public.mcp_gateway.create_time IS '创建时间';
COMMENT ON COLUMN public.mcp_gateway.update_time IS '更新时间';

CREATE INDEX idx_mcp_gateway_status ON public.mcp_gateway (status);

CREATE TRIGGER trg_mcp_gateway_update_time
BEFORE UPDATE ON public.mcp_gateway
FOR EACH ROW
EXECUTE FUNCTION public.update_update_time();

INSERT INTO public.mcp_gateway (id, gateway_id, gateway_name, gateway_desc, status, create_time, update_time)
VALUES
  (1, 'gateway_001', '员工信息查询网关', '用于查询公司员工信息的MCP网关', 1, now(), now());

SELECT setval(pg_get_serial_sequence('public.mcp_gateway', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.mcp_gateway), (SELECT COUNT(*) > 0 FROM public.mcp_gateway));

CREATE TABLE public.mcp_gateway_auth (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  gateway_id varchar(64) NOT NULL,
  api_key varchar(128),
  rate_limit integer DEFAULT 1000,
  expire_time timestamp,
  status smallint NOT NULL DEFAULT 1,
  create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_mcp_gateway_auth PRIMARY KEY (id),
  CONSTRAINT uk_user_gateway UNIQUE (gateway_id)
);

COMMENT ON TABLE public.mcp_gateway_auth IS '用户网关权限表';
COMMENT ON COLUMN public.mcp_gateway_auth.id IS '主键ID';
COMMENT ON COLUMN public.mcp_gateway_auth.gateway_id IS '网关ID';
COMMENT ON COLUMN public.mcp_gateway_auth.api_key IS 'API密钥';
COMMENT ON COLUMN public.mcp_gateway_auth.rate_limit IS '速率限制（次/小时）';
COMMENT ON COLUMN public.mcp_gateway_auth.expire_time IS '过期时间';
COMMENT ON COLUMN public.mcp_gateway_auth.status IS '状态：0-禁用，1-启用';
COMMENT ON COLUMN public.mcp_gateway_auth.create_time IS '创建时间';
COMMENT ON COLUMN public.mcp_gateway_auth.update_time IS '更新时间';

CREATE INDEX idx_mcp_gateway_auth_gateway_id ON public.mcp_gateway_auth (gateway_id);
CREATE INDEX idx_mcp_gateway_auth_api_key ON public.mcp_gateway_auth (api_key);

CREATE TRIGGER trg_mcp_gateway_auth_update_time
BEFORE UPDATE ON public.mcp_gateway_auth
FOR EACH ROW
EXECUTE FUNCTION public.update_update_time();

INSERT INTO public.mcp_gateway_auth (id, gateway_id, api_key, rate_limit, expire_time, status, create_time, update_time)
VALUES
  (1, 'gateway_001', 'RS590LKPOD8877DDLMFKS4', 1000, now(), 1, now(), now());

SELECT setval(pg_get_serial_sequence('public.mcp_gateway_auth', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.mcp_gateway_auth), (SELECT COUNT(*) > 0 FROM public.mcp_gateway_auth));

CREATE TABLE public.mcp_protocol_mapping (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  gateway_id varchar(64) NOT NULL,
  tool_id bigint NOT NULL,
  mapping_type varchar(32) NOT NULL,
  parent_path varchar(256),
  field_name varchar(128) NOT NULL,
  mcp_path varchar(256) NOT NULL,
  mcp_type varchar(32) NOT NULL,
  mcp_desc varchar(512),
  is_required smallint NOT NULL DEFAULT 0,
  http_path varchar(256),
  http_location varchar(32) DEFAULT 'body',
  sort_order integer DEFAULT 0,
  create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_mcp_protocol_mapping PRIMARY KEY (id)
);

COMMENT ON TABLE public.mcp_protocol_mapping IS 'MCP映射配置表';
COMMENT ON COLUMN public.mcp_protocol_mapping.id IS '主键ID';
COMMENT ON COLUMN public.mcp_protocol_mapping.gateway_id IS '所属网关ID';
COMMENT ON COLUMN public.mcp_protocol_mapping.tool_id IS '所属工具ID';
COMMENT ON COLUMN public.mcp_protocol_mapping.mapping_type IS '映射类型：request-请求参数映射，response-响应数据映射';
COMMENT ON COLUMN public.mcp_protocol_mapping.parent_path IS '父级路径（如：xxxRequest01，用于构建嵌套结构，根节点为NULL）';
COMMENT ON COLUMN public.mcp_protocol_mapping.field_name IS '字段名称（如：city、company、name）';
COMMENT ON COLUMN public.mcp_protocol_mapping.mcp_path IS 'MCP完整路径（如：xxxRequest01.city、xxxRequest01.company.name）';
COMMENT ON COLUMN public.mcp_protocol_mapping.mcp_type IS 'MCP数据类型：string/number/boolean/object/array';
COMMENT ON COLUMN public.mcp_protocol_mapping.mcp_desc IS 'MCP字段描述';
COMMENT ON COLUMN public.mcp_protocol_mapping.is_required IS '是否必填：0-否，1-是（用于生成required数组）';
COMMENT ON COLUMN public.mcp_protocol_mapping.http_path IS 'HTTP路径（JSON路径，如：company.name 或 data.result，object类型可为空）';
COMMENT ON COLUMN public.mcp_protocol_mapping.http_location IS 'HTTP位置：body/query/path/header（仅对request类型有效）';
COMMENT ON COLUMN public.mcp_protocol_mapping.sort_order IS '排序顺序（同级字段排序）';
COMMENT ON COLUMN public.mcp_protocol_mapping.create_time IS '创建时间';
COMMENT ON COLUMN public.mcp_protocol_mapping.update_time IS '更新时间';

CREATE INDEX idx_mcp_protocol_mapping_tool_id ON public.mcp_protocol_mapping (tool_id);
CREATE INDEX idx_mcp_protocol_mapping_mapping_type ON public.mcp_protocol_mapping (mapping_type);
CREATE INDEX idx_mcp_protocol_mapping_parent_path ON public.mcp_protocol_mapping (parent_path);
CREATE INDEX idx_mcp_protocol_mapping_mcp_path ON public.mcp_protocol_mapping (mcp_path);
CREATE INDEX idx_mcp_protocol_mapping_sort_order ON public.mcp_protocol_mapping (sort_order);

CREATE TRIGGER trg_mcp_protocol_mapping_update_time
BEFORE UPDATE ON public.mcp_protocol_mapping
FOR EACH ROW
EXECUTE FUNCTION public.update_update_time();

INSERT INTO public.mcp_protocol_mapping (id, gateway_id, tool_id, mapping_type, parent_path, field_name, mcp_path, mcp_type, mcp_desc, is_required, http_path, http_location, sort_order, create_time, update_time)
VALUES
  (1, '', 1, 'request', NULL, 'xxxRequest01', 'xxxRequest01', 'object', NULL, 1, NULL, 'body', 1, now(), now()),
  (2, '', 1, 'request', 'xxxRequest01', 'city', 'xxxRequest01.city', 'string', '城市名称,如果是中文汉字请先转换为汉语拼音,例如北京:beijing', 1, 'city', 'body', 1, now(), now()),
  (3, '', 1, 'request', 'xxxRequest01', 'company', 'xxxRequest01.company', 'object', '公司信息,如果是中文汉字请先转换为汉语拼音,例如北京:jd/alibaba', 1, NULL, 'body', 2, now(), now()),
  (4, '', 1, 'request', 'xxxRequest01.company', 'name', 'xxxRequest01.company.name', 'string', '公司名称', 1, 'company.name', 'body', 1, now(), now()),
  (5, '', 1, 'request', 'xxxRequest01.company', 'type', 'xxxRequest01.company.type', 'string', '公司类型', 1, 'company.type', 'body', 2, now(), now()),
  (6, '', 1, 'request', NULL, 'xxxRequest02', 'xxxRequest02', 'object', NULL, 1, NULL, 'body', 2, now(), now()),
  (7, '', 1, 'request', 'xxxRequest02', 'employeeCount', 'xxxRequest02.employeeCount', 'string', '雇员姓名', 1, 'employeeCount', 'body', 1, now(), now());

SELECT setval(pg_get_serial_sequence('public.mcp_protocol_mapping', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.mcp_protocol_mapping), (SELECT COUNT(*) > 0 FROM public.mcp_protocol_mapping));

CREATE TABLE public.mcp_protocol_registry (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  gateway_id varchar(64) NOT NULL,
  tool_id bigint NOT NULL,
  tool_name varchar(128) NOT NULL,
  tool_type varchar(32) NOT NULL DEFAULT 'function',
  tool_description varchar(512),
  http_url varchar(512) NOT NULL,
  http_method varchar(16) NOT NULL DEFAULT 'POST',
  http_headers text,
  timeout integer DEFAULT 30000,
  retry_times smallint DEFAULT 0,
  status smallint NOT NULL DEFAULT 1,
  create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_mcp_protocol_registry PRIMARY KEY (id),
  CONSTRAINT uk_gateway_tool UNIQUE (gateway_id, tool_name)
);

COMMENT ON TABLE public.mcp_protocol_registry IS 'MCP工具注册表';
COMMENT ON COLUMN public.mcp_protocol_registry.id IS '主键ID';
COMMENT ON COLUMN public.mcp_protocol_registry.gateway_id IS '所属网关ID';
COMMENT ON COLUMN public.mcp_protocol_registry.tool_id IS '工具ID';
COMMENT ON COLUMN public.mcp_protocol_registry.tool_name IS 'MCP工具名称（如：JavaSDKMCPClient_getCompanyEmployee）';
COMMENT ON COLUMN public.mcp_protocol_registry.tool_type IS '工具类型：function/resource';
COMMENT ON COLUMN public.mcp_protocol_registry.tool_description IS '工具描述';
COMMENT ON COLUMN public.mcp_protocol_registry.http_url IS 'HTTP接口地址';
COMMENT ON COLUMN public.mcp_protocol_registry.http_method IS 'HTTP请求方法：GET/POST/PUT/DELETE';
COMMENT ON COLUMN public.mcp_protocol_registry.http_headers IS 'HTTP请求头（JSON格式）';
COMMENT ON COLUMN public.mcp_protocol_registry.timeout IS '超时时间（毫秒）';
COMMENT ON COLUMN public.mcp_protocol_registry.retry_times IS '重试次数';
COMMENT ON COLUMN public.mcp_protocol_registry.status IS '状态：0-禁用，1-启用';
COMMENT ON COLUMN public.mcp_protocol_registry.create_time IS '创建时间';
COMMENT ON COLUMN public.mcp_protocol_registry.update_time IS '更新时间';

CREATE INDEX idx_mcp_protocol_registry_gateway_id ON public.mcp_protocol_registry (gateway_id);
CREATE INDEX idx_mcp_protocol_registry_status ON public.mcp_protocol_registry (status);

CREATE TRIGGER trg_mcp_protocol_registry_update_time
BEFORE UPDATE ON public.mcp_protocol_registry
FOR EACH ROW
EXECUTE FUNCTION public.update_update_time();

INSERT INTO public.mcp_protocol_registry (id, gateway_id, tool_id, tool_name, tool_type, tool_description, http_url, http_method, http_headers, timeout, retry_times, status, create_time, update_time)
VALUES
  (1, 'gateway_001', 1, 'JavaSDKMCPClient_getCompanyEmployee', 'function', '获取公司雇员信息', 'http://localhost:8701/api/v1/mcp/get_company_employee', 'POST', '{"Content-Type": "application/json"}', 30000, 0, 1, now(), now());

SELECT setval(pg_get_serial_sequence('public.mcp_protocol_registry', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.mcp_protocol_registry), (SELECT COUNT(*) > 0 FROM public.mcp_protocol_registry));
